sudo: required

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: reactos
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/AmineKhaldi/reactos.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen

git:
  depth: 5

script:
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
