environment:
  NotificationEmail:
    secure: o9L/jPnkAFCv4S9rzzWad566CMR4C83V6u8rIsscmdY=
  ProjectToken:
    secure: egBzPXNqCBXqgT3FqDd7lg==

version: reactos.appveyor.{build}
skip_branch_with_pr: true
clone_depth: 5
clone_folder: c:\reactos-cov

init:
  - ps: (New-Object System.Net.WebClient).DownloadFile("https://svn.reactos.org/amine/RosCMakeNinja.zip","C:\RosCMakeNinja.zip")
  - 7z x C:\RosCMakeNinja.zip -oC:\RosCMakeNinja

build_script:
  - set PATH=C:\RosCMakeNinja\bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86
  - cmake --version
  - md c:\ros_build
  - cd c:\ros_build
  - call %APPVEYOR_BUILD_FOLDER%\configure.cmd
  #- cov-build --dir cov-int ninja -k0 | grep -P -v '\[\d+\/\d+\] '
  - cov-build --dir cov-int ninja -k0 || 7z a -tzip -mm=lzma -mx=9 reactos.zip cov-int || curl --form token=%ProjectToken% --form email=%NotificationEmail% --form file=@reactos.zip --form version="3c1c303" --form description="ReactOS 3c1c303." https://scan.coverity.com/builds?project=reactos
  #- 7z a -tzip -mm=lzma -mx=9 reactos.zip cov-int
  #- git --git-dir=%APPVEYOR_BUILD_FOLDER%\.git rev-parse --short=7 %APPVEYOR_REPO_COMMIT%^^ > commit.tmp
  #- set /p REACTOS_COMMIT= < commit.tmp
  #- curl --form token=%ProjectToken% --form email=%NotificationEmail% --form file=@%APPVEYOR_PROJECT_NAME%.zip --form version="%REACTOS_COMMIT%" --form description="ReactOS %REACTOS_COMMIT%." https://scan.coverity.com/builds?project=reactos
  #- curl --form token=%ProjectToken% --form email=%NotificationEmail% --form file=@reactos.zip --form version="3c1c303" --form description="ReactOS 3c1c303." https://scan.coverity.com/builds?project=reactos

test: off
deploy: off
